// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"RouteHub.Service.Dashboard/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	enthub "RouteHub.Service.Dashboard/ent/hub"
)

// HubDelete is the builder for deleting a Hub entity.
type HubDelete struct {
	config
	hooks    []Hook
	mutation *HubMutation
}

// Where appends a list predicates to the HubDelete builder.
func (hd *HubDelete) Where(ps ...predicate.Hub) *HubDelete {
	hd.mutation.Where(ps...)
	return hd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (hd *HubDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, hd.sqlExec, hd.mutation, hd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (hd *HubDelete) ExecX(ctx context.Context) int {
	n, err := hd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (hd *HubDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(enthub.Table, sqlgraph.NewFieldSpec(enthub.FieldID, field.TypeString))
	if ps := hd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, hd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	hd.mutation.done = true
	return affected, err
}

// HubDeleteOne is the builder for deleting a single Hub entity.
type HubDeleteOne struct {
	hd *HubDelete
}

// Where appends a list predicates to the HubDelete builder.
func (hdo *HubDeleteOne) Where(ps ...predicate.Hub) *HubDeleteOne {
	hdo.hd.mutation.Where(ps...)
	return hdo
}

// Exec executes the deletion query.
func (hdo *HubDeleteOne) Exec(ctx context.Context) error {
	n, err := hdo.hd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{enthub.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hdo *HubDeleteOne) ExecX(ctx context.Context) {
	if err := hdo.Exec(ctx); err != nil {
		panic(err)
	}
}
